spring:
  application:
    name: purchase-service
  output.ansi.enabled: ALWAYS
  datasource:
# online db
    url: ${vars.url}
    username: ${vars.username}
    password: ${vars.pass}
# locale db
#    url: jdbc:postgresql://localhost:5432/purchase
#    username: postgres
#    password: 1945
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      # create-drop only for tests
      ddl-auto: create-drop

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always